version: '3.8'

services:
  # Backend API
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    volumes:
      # - ./database.sqlite:/app/database.sqlite
      - ./logs:/app/logs
      - ./backups:/app/backups
    restart: unless-stopped
    networks:
      - tekinler-network

  # Frontend React App
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - tekinler-network

networks:
  tekinler-network:
    driver: bridge

