version: "3.8"
services:
  app:
    build: .
    container_name: tekinler-app
    ports:
      - "5000:5000"
    env_file: .env
    volumes:
      - ./database.sqlite:/usr/src/app/database.sqlite
    restart: unless-stopped


